### ISSUE TITLE
zerokeeper你好，我对webeye完成了python3代码的升级

### ISSUE THREAD

**Issue by Schweik7** [zerokeeper/WebEye#1]
zerokeeper您好，由于我的环境主要是python3，因此对您的webeye包括pythonwhois进行了一些小的修改让它能够更好地支持python3。我很喜欢您的webeye的小巧实用。请问您会将它发布到pypi吗？请问我可以将代码pull requests吗？

**Comment by zerokeeper** [comment]
好的，可以提交看看。这个项目很长时间没有维护了，暂时不考虑发布到pypi
